### ISSUE TITLE
Feat/Add a delete form feature

### ISSUE THREAD

**Issue by Amogh-Nivaskar** [piyushgarg-dev/review-app-api#32]
### Is your proposal related to a problem?

 The user should be able to delete their created forms.

### Describe the solution you'd like

Currently, when you click on the delete button to delete a form on dashboard, nothing happens. Ideally, the form should get deleted.

I was thinking of adding a static method to FormService class, which will delete the form using prisma client.

![image](https://github.com/piyushgarg-dev/review-app-api/assets/99811918/c326f597-0d24-4485-91bd-acdd8f5a2c65)

**Comment by Amogh-Nivaskar** [comment]
I would like to work on this, can you please assign me this issue.

**Comment by piyushgarg-dev** [comment]
This is not as straightforward as just deleting the form. This code will always throw an error because we have foreign relations with FormSubmissions. We need to clear all the submissions and then delete a form.

Currently, we want to build the core functionality first 😄

Thanks a lot for contributing.
